class Foruby::RealFragment < Foruby::Fragment[Float]
  type primitive = Float

  def +@: () -> instance

  def -@: () -> instance

  def +: (instance | Foruby::IntegerFragment | real) -> instance

  def -: (instance | Foruby::IntegerFragment | real) -> instance

  def *: (instance | Foruby::IntegerFragment | real) -> instance

  def /: (instance | Foruby::IntegerFragment | real) -> instance

  def **: (instance | Foruby::IntegerFragment | real) -> instance

  def abs: () -> instance

  def ==: (instance | Foruby::IntegerFragment | real) -> Foruby::LogicalFragment

  def !=: (instance | Foruby::IntegerFragment | real) -> Foruby::LogicalFragment
end
