module Foruby::Refinement::IntegerRefinement
  def _plus: (Integer | Foruby::IntegerFragment) -> Foruby::IntegerFragment

  def _minus: (Integer | Foruby::IntegerFragment) -> Foruby::IntegerFragment

  def _multiple: (Integer | Foruby::IntegerFragment) -> Foruby::IntegerFragment

  def _divide: (Integer | Foruby::IntegerFragment) -> Foruby::IntegerFragment

  def _abs: () -> Foruby::IntegerFragment

  def _equal: (Integer | Foruby::IntegerFragment) -> Foruby::Fragment[bool]
end
