class TrueClass
  type fragment = Foruby::LogicalFragment

  def &: (fragment) -> fragment | ...

  def |: (fragment) -> fragment | ...

  def ^: (fragment) -> fragment | ...

  def ==: (fragment) -> fragment | ...

  def !=: (fragment) -> fragment | ...
end

class FalseClass
  type fragment = Foruby::LogicalFragment

  def &: (fragment) -> fragment | ...

  def |: (fragment) -> fragment | ...

  def ^: (fragment) -> fragment | ...

  def ==: (fragment) -> fragment | ...

  def !=: (fragment) -> fragment | ...
end
