class Float
  type fragment = Foruby::RealFragment

  def +: (fragment | Foruby::IntegerFragment) -> fragment | ...

  def -: (fragment | Foruby::IntegerFragment) -> fragment | ...

  def *: (fragment | Foruby::IntegerFragment) -> fragment | ...

  def /: (fragment | Foruby::IntegerFragment) -> fragment | ...

  def **: (fragment | Foruby::IntegerFragment) -> fragment | ...

  def ==: (fragment | Foruby::IntegerFragment) -> Foruby::LogicalFragment | ...

  def !=: (fragment | Foruby::IntegerFragment) -> Foruby::LogicalFragment | ...
end
