class Foruby::Builder[T]
  @value: T?
  @is_parameter: bool
  @dimension: Array[int | range[Integer]]?

  def parameter: () -> self

  def dimension: (*(Integer | range[Integer])) -> self

  def set: (?T?) -> Foruby::Fragment[T]

  def declaration: (string) -> Foruby::Fragment[void]
end
