module Foruby::Core
  type fragments = Hash[Binding, Array[Foruby::Fragment[untyped]]]

  @@fragments: fragments
  @@top_binding: Binding

  %a{pure} def self.fragments: -> fragments

  def self.top_binding: -> Binding

  def self.top_binding=: (Binding) -> Binding

  def self.check: (String | Integer | Foruby::Fragment[untyped]) -> void

  def self.push: (String | Foruby::Fragment[untyped], ?bin: Binding?) -> Foruby::Fragment[untyped]

  def self.add_block: (Binding) { () -> void } -> Foruby::Fragment[untyped]
end
