module Foruby::Core
  type scopes = Hash[Binding, Foruby::Scope]

  @@scopes: scopes
  @@top_binding: Binding

  %a{pure} def self.scopes: -> scopes

  def self.top_binding: -> Binding

  def self.top_binding=: (Binding) -> Binding

  def self.check: (String | Integer | Foruby::Fragment[untyped]) -> void

  def self.push: (String | Foruby::Fragment[untyped]) -> Foruby::Fragment[untyped]

  def self.add_block: (Binding) { () -> untyped } -> Foruby::Scope

  def self.add_variable: [T](Symbol name, Foruby::Builder[T] builder) -> Foruby::Fragment[untyped]

  def self.add_function: (Foruby::_Function) -> Foruby::Fragment[untyped]
end
