class Foruby::Fragment[T]
  include _Inspect
  attr_reader code: String
  attr_reader builder: Foruby::Builder[T]?
  attr_accessor variable: Foruby::Variable[T]?

  @code: String
  @buidler: Foruby::Builder[T]?
  @variable: Foruby::Variable[T]?

  def initialize: (code: string, ?builder: Foruby::Builder[T]?) -> untyped
end