module Kernel
  def self?.integer: () -> Foruby::IntegerBuilder

  def self?.logical: () -> Foruby::LogicalBuilder

  def self?.function: [ReturnType < Object] (
    Hash[Symbol, Foruby::Builder[untyped]] parameters,
    Foruby::Builder[ReturnType] return_type
  ) { (*untyped) [self: Object & Foruby::Function::_Self[ReturnType]] -> untyped } -> Foruby::Function[ReturnType]
  | (
    Hash[Symbol, Foruby::Builder[untyped]] parameters
  ) { (*untyped) -> untyped } -> Foruby::VoidFunction

  def self?.use: (String) -> void
               | (String, Hash[Symbol, String]) -> void
               | (String, only: String) -> void
               | (String, only: Hash[Symbol, String]) -> void
               | (String, only: Array[String | Hash[Symbol, String]]) -> void
end
