class Foruby::IntegerBuilder < Foruby::Builder[Integer & Object]
  @fragment: Foruby::IntegerFragment?

  def initialize: () -> void

  def set: (?(int | Foruby::IntegerFragment)?) -> Foruby::IntegerFragment
end
