class Foruby::IntegerFragment < Foruby::Fragment[Integer]
  def +: (instance | Integer) -> instance

  def -: (instance | Integer) -> instance

  def *: (instance | Integer) -> instance

  def /: (instance | Integer) -> instance

  def abs: () -> instance

  def ==: (instance | Integer) -> Foruby::LogicalFragment

  def !=: (instance | Integer) -> Foruby::LogicalFragment
end
