class Foruby::IntegerFragment < Foruby::Fragment[Integer]
  type primitive = Integer

  def +: (instance | primitive) -> instance

  def -: (instance | primitive) -> instance

  def *: (instance | primitive) -> instance

  def /: (instance | primitive) -> instance

  def abs: () -> instance

  def ==: (instance | primitive) -> Foruby::LogicalFragment

  def !=: (instance | primitive) -> Foruby::LogicalFragment
end
