class Foruby::LogicalFragment < Foruby::Fragment[bool]
  type primitive = bool

  def !: () -> instance

  def &: (instance | primitive) -> instance

  def |: (instance | primitive) -> instance

  def ^: (instance | primitive) -> instance

  def ==: (instance | primitive) -> instance

  def !=: (instance | primitive) -> instance

  def self.from: (Foruby::LogicalFragment | primitive) -> instance
end
